[tool.poetry]
name = "montydb"
version = "2.3.11"
description = "Monty, Mongo tinified. MongoDB implemented in Python !"
authors = ["davidlatwe <davidlatwe@gmail.com>"]
license = "BSD-3-Clause License"

[tool.poetry.dependencies]
python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, !=3.6.*, ^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pymongo = "^3.11.4"
lmdb = "^1.2.1"
flake8 = "^3.9.2"
codespell = "^2.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
